# Generated by Django 6.0.4 on 2026-04-18 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seredaApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
